{% set name = "pyulog" %}
{% set version = "0.8.0" %}
{% set sha256 = "2d78bf35b4bb36e3d23efe304e53e199f45aa4788f6668df389f0c41d4c71bf0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/PX4/pyulog/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  entry_points:
    - ulog_extract_gps_dump=pyulog.extract_gps_dump:main
    - ulog_info = pyulog.info:main
    - ulog_messages=pyulog.messages:main
    - ulog_params=pyulog.params:main
    - ulog2csv=pyulog.ulog2csv:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
    - setuptools
  run:
    - python
    - numpy

test:
  requires:
    - ddt
    - nose
    - setuptools
  source_files:
    - test/*
    - setup.py
    - versioneer.py
    - setup.cfg
  commands:
    - python setup.py test
    - ulog_info -h
    - ulog_extract_gps_dump -h
    - ulog_messages -h
    - ulog_params -h
    - ulog2csv -h

about:
  home: https://github.com/PX4/pyulog
  license: BSD 3-Clause
  license_file: LICENSE.md
  summary: Python library to parse ULog files for PX4 autopilots.

extra:
  recipe-maintainers:
    - fredowski
