travis:
  secure:
    BINSTAR_TOKEN: F6Ym58spO2VdrCuPmUXEiw9K1w/Mtngmeft9IAfu1Z9skefrwiGoY4M+clGNSzZajGx8i0EkisyruR33WLZQNhF3KtOyFVNlkhnrUtPyZEk8U8UqFlaC9s/EexEzXK1/nG84HWCFyriSSYmmM5k1kyA6+caPGH3ks0pt70M+g23Dn9TuqfyNRoVryrxIU8ckiSymHGyy05GJdt6GAKlgRa/b4uDKKZRUOcDLrIAaFnTGjkDcU5bIRl7F5A+Fb6WYF2IkUGFW9xwpZGrBTOlF1wsz48UnIwcA58HbUR5Bel6ruGzGy9O/hqQq5Su0+ZEcY/4hbVBSWcmx96OrZp6QdB9m+AHdiV75FAiV3LZTZugwc0oTXZHrTEuJGxKlwo5kGH3Ww8VqjH3J+ATCkN5T0rbsc+EAfY7NkmyFHJK+MF+F+vBzz7V4+bjDbiZHT8yx+3CyrkAAdmv8Zmo3iQC83cCdeWCThKfdj9iA2DXCy21clrdkMlwwRzVQ2Gl56G0HkDiMAgbn+1wODZpe9pvrezNQ33jWHctxaAgMQFnDbX5DRrUBnx2DZAfWwPS0qNGI3pCnZIWPF2jp8+shTV9er9aWRhBlB+dGEh3w01rMhgjO+YXviKPOr/IcBFbTc5nSEKFyhyJE8e5DmD/hLg7zAPMajx3At6AS3v1Dwou9ssQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
