travis:
  secure:
    BINSTAR_TOKEN: XXcGUhUBKwugw9puElMydxshoTDBc4OF1CFG5UNZxgBb/DBjOuEG4svYbJUOP/gk3SSQWIWefczyQc4ErIMW+cq8/tcZ0jTmLcYjbFDWKInXURFYq2gxj9zVRx9y3+/qgUVeqmB7G1yEYOUtOe6ymCZ6/hBJkL87EBsFx0Z54hHqRPsLi9+THrKt9rcwWNQOoUd5k4T+jQWqUsMYwANeBU1WROUb+d2nUxP0xhpZQRmc+CRB66bZ31SyW5TALSbQBQuJW4GXQYCb3m3FKrBmcMKrk6IqLtSjx57GWMtud56AZGRcwrjZf7CUU/gP2sSscPQ/QRQjaCX5qI8a+K+LcuvkrnYKXG8C2d9HnxZBwYVJCFj95gRhggT3fovEp0ra+lsYChh19iyEfpWzZE+Ly0cB/8WpB5fa6RirKaRqVPnBFYuaanRuXV4jLvU3INzwXBxO3eJN17c5U3mv/ZXstNHlIaxJ6dHV0nmjeuvfZ5xdyAHicvcDVNfYXxNamxabYwVxB30fcz/pEAUobF5lwDsRzH0gGchT+9qly56My0wcyCSyjCNOVkJcPY3x2YZE9rzI1/qsX5BzxzIi7X3vCldRwKRYa7+3Hoz1lQntmZLH8N+SRiRZtVzTGRXajMJFGIWDnoCm0mWmJQLsePlUTX6VUVTA/lW52T5SOfturMM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
